# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: regarima.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'regarima.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pydemetra._proto import modelling_pb2 as modelling__pb2  # noqa: F401
from pydemetra._proto import toolkit_pb2 as toolkit__pb2  # noqa: F401

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregarima.proto\x12\x08regarima\x1a\rtoolkit.proto\x1a\x0fmodelling.proto\"\xad\x01\n\nSarimaSpec\x12\x0e\n\x06period\x18\x01 \x01(\x05\x12\x1b\n\x03phi\x18\x02 \x03(\x0b\x32\x0e.jd3.Parameter\x12\t\n\x01\x64\x18\x03 \x01(\x05\x12\x1d\n\x05theta\x18\x04 \x03(\x0b\x32\x0e.jd3.Parameter\x12\x1c\n\x04\x62phi\x18\x05 \x03(\x0b\x32\x0e.jd3.Parameter\x12\n\n\x02\x62\x64\x18\x06 \x01(\x05\x12\x1e\n\x06\x62theta\x18\x07 \x03(\x0b\x32\x0e.jd3.Parameter\"\xf1\x04\n\rRegArimaModel\x12\x38\n\x0b\x64\x65scription\x18\x01 \x01(\x0b\x32#.regarima.RegArimaModel.Description\x12\x36\n\nestimation\x18\x02 \x01(\x0b\x32\".regarima.RegArimaModel.Estimation\x12+\n\x0b\x64iagnostics\x18\x05 \x01(\x0b\x32\x16.modelling.Diagnostics\x1a\xc0\x01\n\x0b\x44\x65scription\x12\x1b\n\x06series\x18\x01 \x01(\x0b\x32\x0b.jd3.TsData\x12\x0b\n\x03log\x18\x02 \x01(\x08\x12\x30\n\rpreadjustment\x18\x03 \x01(\x0e\x32\x19.modelling.LengthOfPeriod\x12\x30\n\tvariables\x18\x04 \x03(\x0b\x32\x1d.modelling.RegressionVariable\x12#\n\x05\x61rima\x18\x05 \x01(\x0b\x32\x14.regarima.SarimaSpec\x1a\xfd\x01\n\nEstimation\x12\t\n\x01y\x18\x01 \x03(\x01\x12\x16\n\x01x\x18\x02 \x01(\x0b\x32\x0b.jd3.Matrix\x12\t\n\x01\x62\x18\x03 \x03(\x01\x12 \n\x0b\x62\x63ovariance\x18\x04 \x01(\x0b\x32\x0b.jd3.Matrix\x12-\n\nparameters\x18\x05 \x01(\x0b\x32\x19.jd3.ParametersEstimation\x12-\n\nlikelihood\x18\x06 \x01(\x0b\x32\x19.jd3.LikelihoodStatistics\x12\x11\n\tresiduals\x18\x07 \x03(\x01\x12.\n\x08missings\x18\x08 \x03(\x0b\x32\x1c.modelling.MissingEstimationB7\n%jdplus.toolkit.base.protobuf.regarimaB\x0eRegArimaProtosP\x00P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'regarima_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%jdplus.toolkit.base.protobuf.regarimaB\016RegArimaProtos'
  _globals['_SARIMASPEC']._serialized_start=61
  _globals['_SARIMASPEC']._serialized_end=234
  _globals['_REGARIMAMODEL']._serialized_start=237
  _globals['_REGARIMAMODEL']._serialized_end=862
  _globals['_REGARIMAMODEL_DESCRIPTION']._serialized_start=414
  _globals['_REGARIMAMODEL_DESCRIPTION']._serialized_end=606
  _globals['_REGARIMAMODEL_ESTIMATION']._serialized_start=609
  _globals['_REGARIMAMODEL_ESTIMATION']._serialized_end=862
# @@protoc_insertion_point(module_scope)
