# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: outliers.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'outliers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()



from pydemetra._proto import toolkit_pb2 as toolkit__pb2  # noqa: F401

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eoutliers.proto\x12\x08outliers\x1a\rtoolkit.proto\"L\n\x07Outlier\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\x05\x12\x13\n\x0b\x63oefficient\x18\n \x01(\x01\x12\x0c\n\x04stde\x18\x0b \x01(\x01\"\xba\x02\n\x10RegArimaSolution\x12\x15\n\rarima_initial\x18\x01 \x03(\x01\x12\x13\n\x0b\x61rima_final\x18\x02 \x03(\x01\x12\x35\n\x12likelihood_initial\x18\x03 \x01(\x0b\x32\x19.jd3.LikelihoodStatistics\x12\x33\n\x10likelihood_final\x18\x04 \x01(\x0b\x32\x19.jd3.LikelihoodStatistics\x12#\n\x08outliers\x18\x05 \x03(\x0b\x32\x11.outliers.Outlier\x12\x14\n\x0c\x63oefficients\x18\x06 \x03(\x01\x12\x1f\n\ncovariance\x18\x07 \x01(\x0b\x32\x0b.jd3.Matrix\x12\x1f\n\nregressors\x18\x08 \x01(\x0b\x32\x0b.jd3.Matrix\x12\x11\n\tresiduals\x18\t \x03(\x01\x42\x37\n%jdplus.toolkit.base.protobuf.outliersB\x0eOutliersProtosP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'outliers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%jdplus.toolkit.base.protobuf.outliersB\016OutliersProtos'
  _globals['_OUTLIER']._serialized_start=43
  _globals['_OUTLIER']._serialized_end=119
  _globals['_REGARIMASOLUTION']._serialized_start=122
  _globals['_REGARIMASOLUTION']._serialized_end=436
# @@protoc_insertion_point(module_scope)
